### ISSUE TITLE
Exception when joining game 

### ISSUE THREAD

**Issue by MelonCode** [MCMDEV/i18n#2]
Greetings! 
Tried to use plugin, however I receive tons of issues similar to stacktrace below when trying to join server 

```[17:27:41 ERROR]: [i18n] Unhandled exception occurred in onPacketSending(PacketEvent) for i18n
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, com.google.common.base.Function)'
	at de.helixdevs.i18n.paper.protocollib.EntityMetadataAdapter.onPacketSending(EntityMetadataAdapter.java:16) ~[i18n-paper-1.0.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib (3).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (3).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib (3).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib (3).jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib (3).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527) ~[ProtocolLib (3).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469) ~[ProtocolLib (3).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib (3).jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2073) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2059) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:274) ~[?:?]
	at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:257) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2393) ~[?:?]
	at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:2052) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:397) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:307) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:326) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:568) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1582) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:27:41 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@20cfb5e6[
    a=43
    b=[net.minecraft.network.syncher.DataWatcher$Item@2bbfd4c, net.minecraft.network.syncher.DataWatcher$Item@46e22aae, net.minecraft.network.syncher.DataWatcher$Item@1ecd7b73, net.minecraft.network.syncher.DataWatcher$Item@43708dc9, net.minecraft.network.syncher.DataWatcher$Item@1e7c4976, net.minecraft.network.syncher.DataWatcher$Item@491ca74d, net.minecraft.network.syncher.DataWatcher$Item@3cff4bfe, net.minecraft.network.syncher.DataWatcher$Item@7b26976d, net.minecraft.network.syncher.DataWatcher$Item@7ed4686, net.minecraft.network.syncher.DataWatcher$Item@2be7aff9, net.minecraft.network.syncher.DataWatcher$Item@6d81b1c0, net.minecraft.network.syncher.DataWatcher$Item@22d3cee2, net.minecraft.network.syncher.DataWatcher$Item@4f676548, net.minecraft.network.syncher.DataWatcher$Item@59e9933a, net.minecraft.network.syncher.DataWatcher$Item@39062676, net.minecraft.network.syncher.DataWatcher$Item@51e4b6a, net.minecraft.network.syncher.DataWatcher$Item@712723a4, net.minecraft.network.syncher.DataWatcher$Item@64421ef9]
  ]
```

Paper 1.19
Latest ProtocolLib dev build 

![image](https://user-images.githubusercontent.com/3682284/183443175-312a42cf-f5de-43aa-9d7d-047be773de26.png)

**Comment by MelonCode** [comment]
The issue was in broken release build on GitHub, from new build or building from source it's fine
