### ISSUE TITLE
Invalid argument makes crash

### ISSUE THREAD

**Issue by Iuriiiii** [MCMDEV/i18n#6]
A translation key with an empty argument makes plugin crash.

Example:

`tpa.request_received=TPA request received from {}.`

where `{}` is the problem.

Error:

```
java.lang.IllegalArgumentException: can't parse argument number:
        at java.text.MessageFormat.makeFormat(MessageFormat.java:1454) ~[?:?]
        at java.text.MessageFormat.applyPattern(MessageFormat.java:492) ~[?:?]
        at java.text.MessageFormat.<init>(MessageFormat.java:391) ~[?:?]
        at de.helixdevs.i18n.common.repositories.FilesTranslationRepository.lambda$load$0(FilesTranslationRepository.java:75) ~[i18n-paper-1.3.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at de.helixdevs.i18n.common.repositories.FilesTranslationRepository.lambda$load$1(FilesTranslationRepository.java:71) ~[i18n-paper-1.3.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at de.helixdevs.i18n.common.repositories.FilesTranslationRepository.load(FilesTranslationRepository.java:55) ~[i18n-paper-1.3.jar:?]
        at de.helixdevs.i18n.common.repositories.FilesTranslationRepository.<init>(FilesTranslationRepository.java:50) ~[i18n-paper-1.3.jar:?]
        at de.helixdevs.i18n.common.platform.I18nPlatform.loadTranslations(I18nPlatform.java:28) ~[i18n-paper-1.3.jar:?]
        at de.helixdevs.i18n.common.platform.I18nPlatform.enable(I18nPlatform.java:22) ~[i18n-paper-1.3.jar:?]
        at de.helixdevs.i18n.paper.I18nPaperPlugin.onEnable(I18nPaperPlugin.java:25) ~[i18n-paper-1.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-408]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-408]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:678) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at java.text.MessageFormat.makeFormat(MessageFormat.java:1452) ~[?:?]
        ... 32 more
```

**Comment by mcmdev** [comment]
The issue here doesn't lie in the plugin, but in the [Java MessageFormat specification](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/MessageFormat.html), which requires a number inside of the curly brackets. The MessageFormat is a requirement of the Adventure library, which this library is essentially just a wrapper around.
